# Speed up your CI by adding caching. 
# Create a GitHub Actions workflow that uses actions/cache@v4 (or newer) to cache dependencies. 
name: Cache Dependencies

on:
    push:
        branches:
            - main
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-c9b44c9

      - name: prime-cache-c9b44c9
        run: echo "Cache hit: ${{ steps.cache.outputs['cache-hit'] }}"